version: '3.8'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    environment:
      - REACT_APP_NAME=michael
    # env_file:
    #   - ./.env
