version: '3.8'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=michael-prod
    ports:
      - '8080:80'
    volumes:
      - ./src:/app/src
    # env_file:
    #   - ./.env
